#include "GLDHitBox_ApplyGameEffect.h"

#include "Components/BoxComponent.h"
#include "AbilitySystemBlueprintLibrary.h"
#include "GLDCharacterBase.h"
#include "Abilities/GameplayAbilityTypes.h"
#include "AbilitySystemComponent.h"
#include "GameFramework/ProjectileMovementComponent.h"



AGLDHitBox_ApplyGameEffect::AGLDHitBox_ApplyGameEffect(const FObjectInitializer& ObjectInitializer)
	:Super(ObjectInitializer)
{
	PrimaryActorTick.bCanEverTick = false;

	HitCollisionRootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("CollisionRootComponent"));
	RootComponent = HitCollisionRootComponent;

	HitDamage = CreateDefaultSubobject<UBoxComponent>((TEXT("HitDamage")));
	HitDamage->SetupAttachment(RootComponent);

	InitialLifeSpan = 4.f;
	bNetLoadOnClient = true;
	bReplicates = true;
	SetReplicatingMovement(true);

	ProjectileMovement = CreateDefaultSubobject<UProjectileMovementComponent>(TEXT("ProjectileMovement"));
	//最大速度
	ProjectileMovement->MaxSpeed = 2000.f;
	//初始速度
	ProjectileMovement->InitialSpeed = 1600.f;
	//关闭重力 ，不关重力就是抛物线
	ProjectileMovement->ProjectileGravityScale = 0.f;
	ProjectileMovement->SetUpdatedComponent(RootComponent);

	ProjectileMovement->SetIsReplicated(true);

	// 默认近程攻击
	HitCollisionType = EGLDHitCollisionType::HITCOLLISIONTYPE_SHORT_RANGE_ATTACK;


}

void AGLDHitBox_ApplyGameEffect::PreInitCollision(AActor* InMyInstigator)
{
	if (!InMyInstigator)
	{
		return;
	}

	FVector ShootDirection = InMyInstigator->GetActorRotation().Vector();


	switch (HitCollisionType)
	{
	case EGLDHitCollisionType::HITCOLLISIONTYPE_SHORT_RANGE_ATTACK:

		ProjectileMovement->MaxSpeed = 0.f;
		ProjectileMovement->InitialSpeed = 0.f;
		ProjectileMovement->ProjectileGravityScale = 0.f;

		break;
	case EGLDHitCollisionType::HITCOLLISIONTYPE_DIRECT_LINE:

		RootComponent->SetWorldRotation(FRotator::ZeroRotator);
		ProjectileMovement->Velocity = ShootDirection * ProjectileMovement->InitialSpeed;

		break;
	case EGLDHitCollisionType::HITCOLLISIONTYPE_LINE:
		break;
	case EGLDHitCollisionType::HITCOLLISIONTYPE_TRACK_LINE:
		break;
	case EGLDHitCollisionType::HITCOLLISIONTYPE_RANGE_LINE:
		break;
	case EGLDHitCollisionType::HITCOLLISIONTYPE_RANGE:
		break;
	case EGLDHitCollisionType::HITCOLLISIONTYPE_CHAIN:
		break;
	default:
		break;
	}


}

void AGLDHitBox_ApplyGameEffect::HandleDamage(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
	if (OtherActor != GetInstigator())
	{
		if (AGLDCharacterBase* InTarget = Cast<AGLDCharacterBase>(OtherActor))
		{
			//必须在服务器
			if (!InTarget->IsNetMode(ENetMode::NM_Client))
			{

				//已经对该对象产生伤害
				if (IsExist(InTarget))
				{
					return;
				}

				//拿到一个GAS
				if (UAbilitySystemComponent* InAbilitySystemComponent = InTarget->GetAbilitySystemComponent())
				{

					//创造一个上下文
					FGameplayEffectContextHandle EffectContext = InAbilitySystemComponent->MakeEffectContext();

					EffectContext.AddInstigator(GetInstigator(), this);
					//添加一个源目标
					EffectContext.AddSourceObject(InTarget);


					//创建一个实例GE， 并得到它的handle
					//GE的类，等级（默认参数用来查询等级不同造成不同的效果）
					FGameplayEffectSpecHandle EffectSpecHandle =
						InAbilitySystemComponent->MakeOutgoingSpec(EffectClass, 1, EffectContext);

					if (EffectSpecHandle.IsValid())
					{
						//应用的实例到目标
						InAbilitySystemComponent->ApplyGameplayEffectSpecToTarget(*EffectSpecHandle.Data.Get(), InAbilitySystemComponent);
					}

					//标记为已处理
					AttackedTarget.AddUnique(InTarget);




				}
			}


		}

	}

}

UPrimitiveComponent* AGLDHitBox_ApplyGameEffect::GetHitDamage()
{
	return HitDamage;
}

void AGLDHitBox_ApplyGameEffect::SetHitDamageRelativePosition(const FVector& InNewPostion)
{
	if (UPrimitiveComponent* InHitComponent = GetHitDamage())
	{
		InHitComponent->SetRelativeLocation(InNewPostion);
	}
}

void AGLDHitBox_ApplyGameEffect::SetBoxExtent(const FVector& InNewBoxExtent)
{
	HitDamage->SetBoxExtent(InNewBoxExtent);
}

bool AGLDHitBox_ApplyGameEffect::IsExist(AGLDCharacterBase* InNewTaget) const
{
	for (auto& Tmp : AttackedTarget)
	{
		if (Tmp.IsValid())
		{
			if (Tmp == InNewTaget)
			{
				return true;
			}
		}
	}

	return false;
}

void AGLDHitBox_ApplyGameEffect::BeginPlay()
{
	Super::BeginPlay();

	if (UPrimitiveComponent* InHitComponent = GetHitDamage())
	{
		InHitComponent->SetHiddenInGame(true);
		InHitComponent->OnComponentBeginOverlap.AddDynamic(this, &AGLDHitBox_ApplyGameEffect::HandleDamage);

	}

}

void AGLDHitBox_ApplyGameEffect::Tick(float DeltaTime)
{

	Super::Tick(DeltaTime);

}
